{% set version = "0.8.0" %}

package:
  name: nbrsessionproxy
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/n/nbrsessionproxy/nbrsessionproxy-{{ version }}.tar.gz
  sha256: e097406453a83cc3663af66d569894a3340126c220bb73b9019879b8bcb105ff

build:
  number: 1000
  skip: True  # [py2k]
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - nbserverproxy >=0.5.1
  run:
    - python
    - notebook
    - nbserverproxy >=0.5.1

test:
  imports:
    - nbrsessionproxy

about:
  home: https://github.com/jupyterhub/nbrsessionproxy
  license: BSD 3-Clause
  license_family: BSD
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.txt'
  summary: Jupyter extension to proxy RStudio's rsession


extra:
  recipe-maintainers:
    - ocefpaf
    - lsetiawan
